CREATE EXTENSION IF NOT EXISTS "pgcrypto";

INSERT INTO products (product_id, name, description, price, category, available_quantity,
                      attributes, created_at, updated_at)
VALUES (gen_random_uuid(), 'School Uniform Shirt',
        'Classic white shirt for school uniforms.', 29.99, 'School Uniforms', 100,
        '{"color": "white", "size": "M"}', NOW(), NOW()),
       (gen_random_uuid(), 'School Uniform Pants',
        'Comfortable black pants for school uniforms.', 39.99, 'School Uniforms', 80,
        '{"color": "black", "size": "32"}', NOW(), NOW()),
       (gen_random_uuid(), 'School Uniform Skirt',
        'Pleated skirt for school uniforms.', 34.99, 'School Uniforms', 60,
        '{"color": "navy", "size": "S"}', NOW(), NOW()),
       (gen_random_uuid(), 'School Uniform Tie',
        'Striped tie for school uniforms.', 14.99, 'School Uniforms', 150,
        '{"color": "red", "pattern": "stripes"}', NOW(), NOW()),
       (gen_random_uuid(), 'School Uniform Blazer',
        'Formal blazer for school uniforms.', 59.99, 'School Uniforms', 40,
        '{"color": "black", "size": "L"}', NOW(), NOW()),
       (gen_random_uuid(), 'School Uniform Sweater',
        'Warm sweater for school uniforms.', 24.99, 'School Uniforms', 90,
        '{"color": "grey", "size": "M"}', NOW(), NOW()),
       (gen_random_uuid(), 'School Uniform Jacket',
        'Rain-resistant jacket for school uniforms.', 49.99, 'School Uniforms', 70,
        '{"color": "blue", "size": "XL"}', NOW(), NOW()),
       (gen_random_uuid(), 'School Uniform Socks',
        'Durable socks for school uniforms.', 5.99, 'School Uniforms', 200,
        '{"color": "white", "size": "One Size"}', NOW(), NOW()),
       (gen_random_uuid(), 'School Uniform Belt',
        'Leather belt for school uniforms.', 19.99, 'School Uniforms', 120,
        '{"color": "brown", "size": "M"}', NOW(), NOW()),
       (gen_random_uuid(), 'School Uniform Hat',
        'Caps for school uniforms.', 9.99, 'School Uniforms', 130,
        '{"color": "black", "size": "One Size"}', NOW(), NOW()),
       (gen_random_uuid(), 'School Uniform Vest',
        'Formal vest for school uniforms.', 29.99, 'School Uniforms', 50,
        '{"color": "navy", "size": "S"}', NOW(), NOW()),
       (gen_random_uuid(), 'School Uniform Gloves',
        'Winter gloves for school uniforms.', 12.99, 'School Uniforms', 110,
        '{"color": "grey", "size": "M"}', NOW(), NOW()),
       (gen_random_uuid(), 'School Uniform Scarf',
        'Warm scarf for school uniforms.', 14.99, 'School Uniforms', 100,
        '{"color": "red", "pattern": "solid"}', NOW(), NOW()),
       (gen_random_uuid(), 'School Uniform Backpack',
        'Durable backpack for school uniforms.', 39.99, 'School Uniforms', 75,
        '{"color": "black", "capacity": "20L"}', NOW(), NOW()),
       (gen_random_uuid(), 'School Uniform Shoes',
        'Comfortable shoes for school uniforms.', 49.99, 'School Uniforms', 65,
        '{"color": "black", "size": "9"}', NOW(), NOW()),
       (gen_random_uuid(), 'School Uniform Tie Clip',
        'Elegant tie clip for school uniforms.', 11.99, 'School Uniforms', 140,
        '{"color": "silver"}', NOW(), NOW()),
       (gen_random_uuid(), 'School Uniform Belt Buckle',
        'Metal belt buckle for school uniforms.', 8.99, 'School Uniforms', 160,
        '{"color": "gold"}', NOW(), NOW()),
       (gen_random_uuid(), 'School Uniform ID Holder',
        'ID card holder for school uniforms.', 7.99, 'School Uniforms', 180,
        '{"color": "blue"}', NOW(), NOW()),
       (gen_random_uuid(), 'School Uniform Water Bottle',
        'Reusable water bottle for school uniforms.', 14.99, 'School Uniforms', 190,
        '{"color": "green", "capacity": "500ml"}', NOW(), NOW()),
       (gen_random_uuid(), 'School Uniform Lunch Box',
        'Insulated lunch box for school uniforms.', 19.99, 'School Uniforms', 170,
        '{"color": "red", "capacity": "1L"}', NOW(), NOW());
